baseURL = "https://kookerella.com/"
languageCode = "en-gb"
title = "kookerella.com"

[params]
  tagline = "Specialist software development consultancy for broadcast & VOD systems"
  email = "admin@kookerella.com"
  github = "https://github.com/kookerella-ltd"

[menu]
  [[menu.main]]
    name = "Learn"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true
